

CREATE TABLE burgers (
id INTEGER(100) NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(100)NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT 0,
date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
PRIMARY KEY (id)
);

