CREATE TABLE burgers (
id INTEGER(100) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR(100)NOT NULL,
devoured BOOLEAN DEFAULT false,
date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);


